USE ShopManagement;
CREATE TABLE Employees
(ID INT PRIMARY KEY IDENTITY(0, 1),
Name NVARCHAR(100) NOT NULL,
Age INT CHECK (Age BETWEEN 18 AND 100),
Gender NCHAR CHECK (Gender IN ('M', 'F')),
PhoneNumber NVARCHAR(15),
Email NVARCHAR(100),
Experience INT CHECK (Experience >= 0),
Position NVARCHAR(50) CHECK (Position IN ('Администратор', 'Менеджер', 'Кассир')),
UserLogin NVARCHAR(50) UNIQUE,
UserPassword VARBINARY(64));

CREATE TABLE Products
(ID INT PRIMARY KEY IDENTITY(0, 1),
Name NVARCHAR(100) NOT NULL,
Price NUMERIC(10, 2) NOT NULL CHECK (Price >= 0) DEFAULT 0,
Amount INT NOT NULL CHECK (Amount >= 0) DEFAULT 0,
Description NVARCHAR(100));

CREATE TABLE Suppliers
(ID INT PRIMARY KEY IDENTITY(0, 1),
Name NVARCHAR(100) NOT NULL,
PhoneNumber NVARCHAR(15),
Email NVARCHAR(100),
AccountNumber NVARCHAR(20));

CREATE TABLE SupplierOrders
(ID INT PRIMARY KEY IDENTITY(0, 1),
SupplierID INT REFERENCES Suppliers ON DELETE SET NULL,
EmployeeID INT REFERENCES Employees ON DELETE SET NULL,
Date DATE NOT NULL);

CREATE TABLE SupplierOrderItems
(ID INT PRIMARY KEY IDENTITY(0, 1),
OrderID INT REFERENCES SupplierOrders ON DELETE CASCADE NOT NULL,
ProductID INT REFERENCES Products ON DELETE SET NULL,
Amount INT NOT NULL CHECK (Amount > 0) DEFAULT 1,
Price NUMERIC(10, 2) NOT NULL CHECK (Price >= 0) DEFAULT 0)

CREATE TABLE SupplierReturnItems
(ID INT PRIMARY KEY IDENTITY(0, 1),
OrderItemID INT REFERENCES SupplierOrderItems ON DELETE CASCADE NOT NULL,
Amount INT NOT NULL CHECK (Amount > 0) DEFAULT 1,
EmployeeID INT REFERENCES Employees ON DELETE SET NULL,
Reason VARCHAR(150),
Date DATE NOT NULL);

CREATE TABLE Customers
(ID INT PRIMARY KEY IDENTITY(0, 1),
Name NVARCHAR(100) NOT NULL,
PhoneNumber NVARCHAR(15),
Email NVARCHAR(100));

CREATE TABLE CustomerOrders
(ID INT PRIMARY KEY IDENTITY(0, 1),
CustomerID INT REFERENCES Customers ON DELETE SET NULL,
EmployeeID INT REFERENCES Employees ON DELETE SET NULL,
Date DATE NOT NULL);

CREATE TABLE CustomerOrderItems
(ID INT PRIMARY KEY IDENTITY(0, 1),
OrderID INT REFERENCES CustomerOrders ON DELETE CASCADE NOT NULL,
ProductID INT REFERENCES Products ON DELETE SET NULL,
Amount INT NOT NULL CHECK (Amount > 0) DEFAULT 1,
Price NUMERIC(10, 2) NOT NULL CHECK (Price >= 0) DEFAULT 0)

CREATE TABLE CustomerReturnItems
(ID INT PRIMARY KEY IDENTITY(0, 1),
OrderItemID INT REFERENCES CustomerOrderItems ON DELETE CASCADE NOT NULL,
Amount INT NOT NULL CHECK (Amount > 0) DEFAULT 1,
EmployeeID INT REFERENCES Employees ON DELETE SET NULL,
Reason VARCHAR(150),
Date DATE NOT NULL);