USE ShopManagement;
CREATE TABLE Employees
(ID INT PRIMARY KEY IDENTITY(0, 1),
Name NVARCHAR(100) NOT NULL,
Age INT CHECK (Age >= 18 AND Age <= 100),
Gender NCHAR CHECK (Gender IN ('М', 'Ж', 'M', 'F')),
PhoneNumber NVARCHAR(15),
Email NVARCHAR(100),
Experience INT CHECK (Experience >= 0),
Position NVARCHAR(50) CHECK (Position IN ('Администратор', 'Менеджер', 'Кассир')),
UserLogin NVARCHAR(50) UNIQUE,
UserPassword VARBINARY(64));

CREATE TABLE Products
(ID INT PRIMARY KEY IDENTITY(0, 1),
Name NVARCHAR(100) NOT NULL,
Price NUMERIC(10, 2) NOT NULL CHECK (Price >= 0) DEFAULT 0,
Amount INT NOT NULL CHECK (Amount >= 0) DEFAULT 0,
Description NVARCHAR(100));

CREATE TABLE Suppliers
(ID INT PRIMARY KEY IDENTITY(0, 1),
Name NVARCHAR(100) NOT NULL, PhoneNumber NVARCHAR(15),
Email NVARCHAR(100),
AccountNumber NVARCHAR(20));

CREATE TABLE SupplierOrders
(ID INT PRIMARY KEY IDENTITY(0, 1),
SupplierID INT REFERENCES Suppliers ON DELETE SET NULL,
EmployeeID INT REFERENCES Employees ON DELETE SET NULL,
Date DATE NOT NULL);

CREATE TABLE SupplierOrderDetails
(ID INT PRIMARY KEY IDENTITY(0, 1),
OrderID INT REFERENCES SupplierOrders ON DELETE CASCADE NOT NULL,
ProductID INT REFERENCES Products ON DELETE SET NULL,
Amount INT NOT NULL CHECK (Amount > 0) DEFAULT 1,
Price NUMERIC(10, 2) NOT NULL CHECK (Price >= 0) DEFAULT 0,
ReturnedAmount INT NOT NULL CHECK (ReturnedAmount >= 0) DEFAULT 0);

CREATE TABLE SupplierReturns
(ID INT PRIMARY KEY IDENTITY(0, 1),
SupplierOrderDetailID INT REFERENCES SupplierOrderDetails ON DELETE CASCADE NOT NULL,
Amount INT NOT NULL CHECK (Amount > 0) DEFAULT 1,
EmployeeID INT REFERENCES Employees ON DELETE SET NULL, Date DATE);

CREATE TABLE Customers
(ID INT PRIMARY KEY IDENTITY(0, 1),
Name NVARCHAR(100) NOT NULL,
PhoneNumber NVARCHAR(15),
Email NVARCHAR(100));

CREATE TABLE CustomerOrders
(ID INT PRIMARY KEY IDENTITY(0, 1),
CustomerID INT REFERENCES Customers ON DELETE SET NULL,
EmployeeID INT REFERENCES Employees ON DELETE SET NULL,
Date DATE NOT NULL);

CREATE TABLE CustomerOrderDetails
(ID INT PRIMARY KEY IDENTITY(0, 1),
OrderID INT REFERENCES CustomerOrders ON DELETE CASCADE NOT NULL,
ProductID INT REFERENCES Products ON DELETE SET NULL,
Amount INT NOT NULL CHECK (Amount > 0) DEFAULT 1,
Price NUMERIC(10, 2) NOT NULL CHECK (Price >= 0) DEFAULT 0,
ReturnedAmount INT NOT NULL CHECK (ReturnedAmount >= 0) DEFAULT 0);

CREATE TABLE CustomerReturns
(ID INT PRIMARY KEY IDENTITY(0, 1),
CustomerOrderDetailID INT REFERENCES CustomerOrderDetails ON DELETE CASCADE NOT NULL,
Amount INT NOT NULL CHECK (Amount > 0) DEFAULT 1,
EmployeeID INT REFERENCES Employees ON DELETE SET NULL,
Date DATE);